apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otelcol
  namespace: opentelemetry
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-targetallocator-sa
    prometheusCR:
      enabled: true
      ## If uncommented, only service monitors with this label will get picked up
      # serviceMonitorSelector:
      #   app: my-app
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 30s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]
        target_allocator:
          endpoint: http://otelcol-targetallocator.opentelemetry.svc.cluster.local
          interval: 30s
          collector_id: "${POD_NAME}"

    processors:
      batch:

    exporters:
      otlphttp:
        endpoint: http://tempo.default.svc.cluster.local:4318
      prometheusremotewrite:
        endpoint: http://vmsingle-victoria-metrics-single-server.default.svc.cluster.local:8428/api/v1/write
      logging:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [prometheusremotewrite]

# Look to https://github.com/lightstep/opentelemetry-examples/blob/main/config/example-collector-config.yaml for more configs