apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation-golang
  namespace: opentelemetry
spec:
  exporter:
    endpoint: http://otelcol-collector.opentelemetry.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"